### ISSUE TITLE
Image being squashed on Safari

### ISSUE THREAD

**Issue by wayne-shih** [primer/design#141]
image on this page https://primer.style/design/tools/figma is being squashed on safari; appears normal on chrome + firefox. 

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/51947763/104530556-15162c80-5671-11eb-9d23-1ab3d68c6e18.png">
<img width="1682" alt="image" src="https://user-images.githubusercontent.com/51947763/104530573-1b0c0d80-5671-11eb-93a2-067ca760b98f.png">

I'm running Safari Version 14.0.3 (16610.4.2) on macOS Big Sur 11.2 Beta (20D5029f) 

but also tested on Safari Version 13.1.2 (15609.3.5.1.3) on macOS Catalina Version 10.15.6 (19G2021) and it's the same thing... 

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/51947763/104530702-69b9a780-5671-11eb-9706-e9e9f8cbcff4.png">

**Comment by yaili** [comment]
Thank you for flagging this, @wayne-shih!

**Comment by juliyvchirkov** [comment]
I can confirm the issue

The default browser `Safari // Release 14.0.3 (16610.4.3.1.4)` on `macOS Big Sur // Release 11.2.1` behaves the same way and stretches the images dreadfully

<img src="https://i.imgur.com/aRxgxSD.png" width="75%">
<img src="https://i.imgur.com/3K0heoJ.png" width="75%">

on the other hand I can report that `Safari Technology Preview // Release 120 (Safari 14.2, WebKit 16612.1.2.6)` renders the same content correctly

<img src="https://i.imgur.com/tH3BeF9.png" width="75%">
<img src="https://i.imgur.com/q7R9au8.png" width="75%">

**Comment by yaili** [comment]
I can't replicate it anymore either.
