### ISSUE TITLE
Outdated links

### ISSUE THREAD

**Issue by AndrisJefimovs** [primer/design#143]
Links to Figma ressources in the [tools page](https://primer.style/design/tools/figma) are redirecting to Figma's File not found page.

**Comment by simurai** [comment]
Does the [Primer Figma Community page](https://www.figma.com/@primer) link work?

I think the rest are only internal links, see note at the top:

> Access to the GitHub Figma organization is currently only available to members of the GitHub team. 

/cc @ashygee

**Comment by ashygee** [comment]
This is correct @simurai. The only link available for public consumption is Primer's community profile on Figma. From there our community library files for Primer Web, Primer Primitives, and Octicons can be accessed @AndrisJefimovs 😁 

We also have recently created a public repository at https://github.com/primer/figma which we will add to our documentation. Thanks for being proactive and sending us feedback!
