### ISSUE TITLE
Expand "Applying Typography" - Typography Guidelines

### ISSUE THREAD

**Issue by jhuashao** [primer/design#19]
> Just linking to components isn't super helpful. We should show components when giving examples on how to use typography. I'd like this to be replaced with a section on "Applying typography" with examples of it in practice, in components and chunks of UI. However I think that could be a lot of work and would be happy if you make an issue for that for now and we follow up with that at a later date.

_Originally posted by @broccolini in https://github.com/primer/design/pull/15_

**11.28.2018**
'Applying Typography' section has been added. This can be expanded in future iterations to house visual usages. Possibly as sub-section called “In Use” or “Use Cases” or something

**Comment by yaili** [comment]
The typography section has been expanded from just "Applying typography" --> https://primer.style/design/foundations/typography
