### ISSUE TITLE
Banner Illustration updates (static)

### ISSUE THREAD

**Issue by ashygee** [primer/design#28]
### Updates to be made
- Header Image
  - @jhuashao and I are pairing to update the header image/animation to be more inline with [Primer Components](https://primer.style/components) and [Primer CSS](https://primer-css.now.sh/css). 
- Header font-weight
  - Currently set to `700`. Should this be `600` as seen on Primer CSS or leave as is which is in line with Primer Components? (cc @broccolini)

**Comment by jhuashao** [comment]
Attached below is a finalized version of my design adapted to Ash's illustration guidelines. This is open for revision and feedback! I will begin animating it, but am still open to suggestions and critique ✨ 

Figma: https://www.figma.com/file/ODURCvr6uUEfT5HzgvMZUggy/Header-Illustrations?node-id=70%3A16

![primer guidelines header](https://user-images.githubusercontent.com/24916540/52679987-c3485300-2eeb-11e9-8973-d2fd7f2fb8b3.jpg)

**Comment by broccolini** [comment]
Wow this looks great 😍 I like that it doesn't feel too different but also feels more right :)

> Currently set to `700`. Should this be `600` as seen on Primer CSS or leave as is which is in line with Primer Components? (cc @broccolini)

700 is not part of our Primer typography styles, it should be `600` everywhere! If it's wrong on Components please open an issue to get that updated too!

**Comment by ashygee** [comment]
@jhuashao Let's ship this!!!! 😀

**Comment by jhuashao** [comment]
Sounds great! Animating with previous styles as we speak right now. Will try to ship it live before our weekly meeting! @ashygee @broccolini
