### ISSUE TITLE
Document Figma components

### ISSUE THREAD

**Issue by broccolini** [primer/design#3]
- how and where to access Primer components in Figma
- tips & tricks
- prototyping in Figma
- useful links (such as Figma docs, spectrum.chat, and helpful articles)
- how to get access to Figma

**Comment by yaili** [comment]
Is [this page](https://primer.style/design/tools/figma) the answer to this issue? Or different?

**Comment by yaili** [comment]
Closing for now. We can create a new issue for improvements to the existing page.
