### ISSUE TITLE
Remove empty pages

### ISSUE THREAD

**Issue by emplums** [primer/design#42]
Color & design tools

**Comment by yaili** [comment]
@emplums like [this](https://primer.style/design/tools)? Feels like we need a template for these landing/directory pages almost

**Comment by emplums** [comment]
Yep! I never quite know what kind of content to put on these pages 🤔

**Comment by yaili** [comment]
Something like this is nice and simple: https://evergreen.segment.com/components/
But we could think of something that requires less maintenance.

**Comment by yaili** [comment]
I'm closing this and tracking in an index page issue https://github.com/primer/doctocat/issues/121
