### ISSUE TITLE
Invalid labels in textarea anatomy image

### ISSUE THREAD

**Issue by eranishojha** [primer/design#515]
I noticed a potential issue with the textarea anatomy image. It appears that the labels "Validation" and "Caption" are mistakenly swapped in the image. To clarify, I believe the label "Validation" should actually be labeled as "Caption," and vice versa.

I have attached a screenshot for reference and also provided a link below to the image. Could you please take a look and verify if this is indeed an error?

**Link:** 
https://primer.style/design/components/textarea#anatomy

**Screenshot:** 
![image](https://github.com/primer/design/assets/28804810/092b1cf3-ca93-4c7a-815f-750607432574)

**Edit**
I found the same issue in the text input anatomy image too.
https://primer.style/design/components/text-input
![image](https://github.com/primer/design/assets/28804810/66b55394-8135-4a79-988a-8b162e8e1fbc)

This is the correct one
https://primer.style/design/components/select
![image](https://github.com/primer/design/assets/28804810/e34948d5-b447-4936-8413-b6c928e1272f)

**Comment by dylanatsmith** [comment]
Thanks for the report @eranishojha. This should be fixed now.
