### ISSUE TITLE
Broken image links in icon design guidelines

### ISSUE THREAD

**Issue by gavinmn** [primer/design#572]
It seems like the image links in https://github.com/primer/design/blob/main/content/foundations/icons/design-guidelines.mdx are no longer working

![Image](https://github.com/primer/design/assets/59900904/d36321c1-6b0a-4e1c-b4aa-c861eed667c8)

**Comment by josepmartins** [comment]
Hey @gavinmn thanks for the heads up. Adding more context to the issue, the URLs in src appear to be broken as they’re not hosted on GitHub, they’re hosted on https://compai.pub/, which appears to be a broken Netlify site. We need to re-upload them.

Slack thread: https://github.slack.com/archives/C03L4CK58BC/p1693232293826019

We'll take a look at it as soon as possible 👍

**Comment by emilybrick** [comment]
For posterity, Figma source images are here: https://www.figma.com/file/2rjsQp42uKvzPXzLZIqOeA/Octicons-v2---Source?type=design&node-id=3064%3A1807&mode=design&t=vhZUsuTQweKsx2k7-1

**Comment by josepmartins** [comment]
Closing as the issue was fixed here: https://github.com/primer/design/pull/585
