### ISSUE TITLE
Question: Are pure CSS style components deprecated?

### ISSUE THREAD

**Issue by vicaba** [primer/design#584]
Hello,

Apologies in advance. I while ago I was able to use primer css "standalone", meaning that I could, for example, import the styles via CDN and then there was a website (an official one) where I could find the desired component in css and copy-paste the html-css code. Is that deprecated? Or am I just not capable of finding the proper documentation site?

Thank you,

**Comment by langermank** [comment]
Hey @vicaba! You can still use Primer CSS as a standalone library. Internally at GH we use [Primer View Components](https://github.com/primer/view_components) as a companion to Primer CSS, and use of CSS alone isn't recommended. Primer CSS is in maintenance mode and is unlikely to receive new component CSS or any large updates. You can still access the older docs [here in Storybook](https://primer.style/css/storybook/?path=/docs/introduction--docs), or reference View Components for markup.

I'm going to close this issue but feel free to reopen if you have any further questions/concerns!

**Comment by vicaba** [comment]
Hello, sorry I missed your answer.
Thank you for your explanation, it is clear now.
