### ISSUE TITLE
I propose to add an IntelIJ trick that allows you to convert strings such as

### ISSUE THREAD

**Issue by Volimjasnu12** [primer/design#871]
I propose to add an IntelIJ trick that allows you to convert strings such as
`const int i = 1;` to such  `(int) i() asm "PUSHINT 1" ` and vice versa.
This will help to refactor the code more conveniently and make it more gas-efficient.

_Originally posted by @MicroNovaX in https://github.com/ton-blockchain/intellij-ton/issues/103_

_Originally posted by @Volimjasnu12 in https://github.com/ton-blockchain/minter-contract/issues/110_

**Comment by ajh123** [comment]
This repoistory doesn't contain any C code. Also `(int) i() asm "PUSHINT 1"` is not IntelIJ specific, it is a feature of C like languages.

What `(int) i() asm "PUSHINT 1" ` does is push an integer on to the stack with the value of 1. Also, why would this help with string convertion?

You also don't need create a duplicated issue (#872) - that is called spam.
