### ISSUE TITLE
broken figma resources link

### ISSUE THREAD

**Issue by pjpimentel** [primer/design#90]
hello!

all the links to figma resources listed in: https://primer.style/design/tools/figma#Resources are broken (at least to me)

Broken link sample: https://www.figma.com/file/WARYmZzsypbLrC6CDyE29dRA/primer-navigation

are the figma links updated?

**Comment by yaili** [comment]
Thanks for submitting this issue, @pjpimentel. Because we switched to a Figma org, the links need to be updated so they allow view-only. We'll let you know once that's fixed.

**Comment by samuria** [comment]
Are all the components being redesigned in Figma? If it is actually just a case of updating the links, please provide them so we can create a PR.

**Comment by pjpimentel** [comment]
hey @yaili, any news?

**Comment by ashygee** [comment]
HI @pjpimentel, because we've transitioned some accounts we have some permissions issues to resolve. We will update with a community file in the coming weeks. Sorry about that!

**Comment by pjpimentel** [comment]
> HI @pjpimentel, because we've transitioned some accounts we have some permissions issues to resolve. We will update with a community file in the coming weeks. Sorry about that!

@ashygee don't worry, thanks!

**Comment by ashygee** [comment]
@pjpimentel Just wanted to make sure you saw this quick update. Thanks for making us aware of the permissions issues with the broken links. I’m going to close this as we’ve explained the update in the PR.
